name: "Upload GitHub Action workflows logs to AWS OpenSearch"
description: "Downloads the workflow logs and uploads to AWS OpenSearch"
author: "Shahar Glazner,Heph Adams"
inputs:
  github_token:
    description: "GitHub PAT"
  github_org:
    description: "The github organization to read the workflows logs from"
  github_repository:
    description: "The github repository to read the workflows logs from"
  github_run_id:
    description: "The workflow specific run id to read the logs from"
  search_host:
    description: "The opensearch host"
  search_index:
    description: "The opensearch index"

outputs:
  result:
    description: "Result"
runs:
  using: "docker"
  image: "Dockerfile"
